FROM oven/bun:alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./apps/web/package.json ./apps/web/package.json 
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock
COPY ./packages/eslint-config/package.json ./packages/eslint-config/package.json 
COPY ./packages/typescript-config/package.json ./packages/typescript-config/package.json

RUN bun install --frozen-lockfile

COPY . .

EXPOSE 3000

CMD [ "bun", "run", "frontend:start" ]