FROM oven/bun:alpine

WORKDIR /app

COPY ./package.json ./package.json
COPY ./apps/backend/package.json ./apps/backend/package.json 
COPY ./turbo.json ./turbo.json
COPY ./bun.lock ./bun.lock

RUN bun install --frozen-lockfile

COPY . .

EXPOSE 4000

CMD [ "bun", "run", "backend:start" ]